//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUP_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Numer_order { get; set; }
        public int ID_sostav { get; set; }
        public System.DateTime Date_order { get; set; }
        public System.DateTime Date_delivery { get; set; }
        public int Adress_PVZ { get; set; }
        public int Glient_FIO { get; set; }
        public int Code { get; set; }
        public int Status_order { get; set; }
        public int ID_order { get; set; }
    
        public virtual FIO FIO { get; set; }
        public virtual PVZ PVZ { get; set; }
        public virtual Sostav Sostav { get; set; }
        public virtual Status Status { get; set; }
    }
}
