//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUP_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Sostav = new HashSet<Sostav>();
        }
    
        public int ID { get; set; }
        public string Articuls { get; set; }
        public int Title_product { get; set; }
        public string Unit { get; set; }
        public short Cost { get; set; }
        public int Supplier { get; set; }
        public int Manufacture { get; set; }
        public int Category { get; set; }
        public int Discount { get; set; }
        public int Count { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Manufacture Manufacture1 { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        public virtual Title Title { get; set; }
        public virtual ICollection<Sostav> Sostav { get; set; }
    }
}
