//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUP_
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVZ
    {
        public PVZ()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID { get; set; }
        public int Index_PVZ { get; set; }
        public string State { get; set; }
        public int Street { get; set; }
        public int Home { get; set; }
    
        public virtual Home_Number Home_Number { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Street Street1 { get; set; }
    }
}
