//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUP_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sostav
    {
        public Sostav()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public string Sostav_order { get; set; }
        public Nullable<int> ID_number_order { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> ID_articul_product { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Product Product { get; set; }
    }
}
