//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUP_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Street
    {
        public Street()
        {
            this.PVZ = new HashSet<PVZ>();
        }
    
        public string Street1 { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<PVZ> PVZ { get; set; }
    }
}
