//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUP_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public Nullable<int> Role_users { get; set; }
        public Nullable<int> FIO { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual FIO FIO1 { get; set; }
        public virtual Role Role { get; set; }
    }
}
